import QuantityRepresentationFoundations

/-!
# Kernel audit surface

The first public results are intentionally free of quotient, remainder,
positional, and carry primitives.  These commands expose their logical axioms.
-/

#print axioms QuantityRepresentationFoundations.finiteState_obstructs_faithfulRepresentation
#print axioms QuantityRepresentationFoundations.finiteState_forces_collision
#print axioms QuantityRepresentationFoundations.noFaithfulEncoding_into_finite
#print axioms QuantityRepresentationFoundations.finiteLocal_and_finiteAuxiliary_still_obstruct_faithfulness
#print axioms QuantityRepresentationFoundations.sameLocal_forces_extension_difference
#print axioms QuantityRepresentationFoundations.finiteLocal_forces_information_into_extension
#print axioms QuantityRepresentationFoundations.faithfulFiniteLocal_forces_infiniteExtension
#print axioms QuantityRepresentationFoundations.finiteFixedDepthTower_obstructs_faithfulness
#print axioms QuantityRepresentationFoundations.noFaithfulEncoding_into_fixedFiniteDepthTower
#print axioms QuantityRepresentationFoundations.finitePrefix_obstructs_faithfulness
#print axioms QuantityRepresentationFoundations.finitePrefix_forces_collision
#print axioms QuantityRepresentationFoundations.faithfulLayeredEncoding_forces_late_difference
#print axioms QuantityRepresentationFoundations.faithfulLayeredEncoding_has_arbitrarily_late_information
#print axioms QuantityRepresentationFoundations.faithfulLayeredEncoding_has_difference
#print axioms QuantityRepresentationFoundations.exists_firstDistinguishingDepth
#print axioms QuantityRepresentationFoundations.firstDifferenceAt_unique
#print axioms QuantityRepresentationFoundations.existsUnique_firstDistinguishingDepth
#print axioms QuantityRepresentationFoundations.faithfulFiniteLayerEncoding_has_unbounded_firstDistinguishingDepth
#print axioms QuantityRepresentationFoundations.unitTrajectory_forces_localRecurrence
#print axioms QuantityRepresentationFoundations.localRecurrence_states_ne
#print axioms QuantityRepresentationFoundations.unitTrajectory_localRecurrence_forces_extensionDifference
#print axioms QuantityRepresentationFoundations.unitTrajectory_has_arbitrarily_late_localRecurrence
#print axioms QuantityRepresentationFoundations.unitTrajectory_has_arbitrarily_late_extensionDifference
#print axioms QuantityRepresentationFoundations.autonomousLocalDynamics_orbit
#print axioms QuantityRepresentationFoundations.autonomousLocalDynamics_has_positiveReturn
#print axioms QuantityRepresentationFoundations.positiveLocalReturn_implies_periodic_readout
#print axioms QuantityRepresentationFoundations.existsUnique_emergentLocalCapacity
#print axioms QuantityRepresentationFoundations.emergentLocalCapacity_periodic_readout
#print axioms QuantityRepresentationFoundations.exists_cycleDecomposition
#print axioms QuantityRepresentationFoundations.cycleDecomposition_before_next_boundary
#print axioms QuantityRepresentationFoundations.cycleDecomposition_unique
#print axioms QuantityRepresentationFoundations.existsUnique_cycleCoordinates
#print axioms QuantityRepresentationFoundations.emergentLocalCapacity_has_unique_cycleCoordinates
#print axioms QuantityRepresentationFoundations.periodicReadout_depends_only_on_residual
#print axioms QuantityRepresentationFoundations.emergentCycleResidual_controls_localReadout
#print axioms QuantityRepresentationFoundations.cycleCoordinatesRec_isCycleDecomposition
#print axioms QuantityRepresentationFoundations.emergentQuotientRemainder_spec
#print axioms QuantityRepresentationFoundations.emergent_decomposition_value
#print axioms QuantityRepresentationFoundations.emergentRemainder_lt
#print axioms QuantityRepresentationFoundations.cycleDecomposition_eq_emergent
#print axioms QuantityRepresentationFoundations.emergent_step_inside_cycle
#print axioms QuantityRepresentationFoundations.emergent_step_at_boundary
#print axioms QuantityRepresentationFoundations.emergent_step_dichotomy
#print axioms QuantityRepresentationFoundations.emergentLocalCapacity_quotientRemainder_spec
#print axioms QuantityRepresentationFoundations.emergentRemainder_controls_localReadout
