import QuantityRepresentationFoundations

#print axioms QuantityRepresentationFoundations.LosslessCompressedWindow.card_eq_windowSize
#print axioms QuantityRepresentationFoundations.LosslessCompressedWindow.encode_bijective
#print axioms QuantityRepresentationFoundations.LosslessCompressedWindow.windowSuccessor_eq_zero_iff_carry
#print axioms QuantityRepresentationFoundations.LosslessCompressedWindow.codeSuccessor_unique
#print axioms QuantityRepresentationFoundations.LosslessCompressedWindow.exact_successor_wrap_iff_carry
#print axioms QuantityRepresentationFoundations.canonicalDepthProjectionLE_unique
#print axioms QuantityRepresentationFoundations.LosslessCompressedTower.universal_projective_tower_laws
#print axioms QuantityRepresentationFoundations.universal_optimal_lossless_representation_collapses_to_carry
#print axioms QuantityRepresentationFoundations.any_two_optimal_lossless_towers_are_projectively_equivalent
