import QuantityRepresentationFoundations.IteratedEmergentPositionalExpansion

/-!
# Canonical emergent digit list

The previous layer proved that every quantity admits a finite positional
expansion obtained by iterating the emergent quotient/remainder transport.
This module packages that construction into a canonical finite digit list.

The list is defined recursively from the already-derived dynamics:

* zero is represented by the empty list;
* for a positive quantity `n`, the head digit is `emergentRemainder b n`;
* the tail is the emergent digit list of `emergentQuotient b n`.

No call to `Nat.digits` occurs in this construction.  Only after proving exact
value reconstruction, digit admissibility, and absence of a leading zero do we
identify the emergent list with the standard canonical `Nat.digits` list.
-/

namespace QuantityRepresentationFoundations

/--
Canonical digit list generated by repeated emergent quotient/remainder
transport.  Digits are little-endian, from least to most significant.
-/
def emergentDigits (b : ℕ) (hb : 1 < b) (n : ℕ) : List ℕ :=
  if hn : n = 0 then
    []
  else
    emergentRemainder b n :: emergentDigits b hb (emergentQuotient b n)
termination_by n
decreasing_by
  exact emergentQuotient_lt_self b n hb (Nat.pos_of_ne_zero hn)

@[simp] theorem emergentDigits_zero (b : ℕ) (hb : 1 < b) :
    emergentDigits b hb 0 = [] := by
  simp [emergentDigits]

/-- Positive quantities expose one residual digit and recurse on the transported tail. -/
theorem emergentDigits_of_pos
    (b n : ℕ) (hb : 1 < b) (hn : 0 < n) :
    emergentDigits b hb n =
      emergentRemainder b n :: emergentDigits b hb (emergentQuotient b n) := by
  rw [emergentDigits]
  simp [ne_of_gt hn]

/-- The emergent digit list is empty exactly for the zero quantity. -/
theorem emergentDigits_ne_nil_iff_ne_zero
    (b n : ℕ) (hb : 1 < b) :
    emergentDigits b hb n ≠ [] ↔ n ≠ 0 := by
  by_cases hn : n = 0
  · subst n
    simp
  · have hnpos : 0 < n := Nat.pos_of_ne_zero hn
    rw [emergentDigits_of_pos b n hb hnpos]
    simp [hn]

/--
The emergent digit list reconstructs the original quantity exactly under the
raw positional evaluator of `carry-geometry`.
-/
theorem rawExpansionValue_emergentDigits
    (b n : ℕ) (hb : 1 < b) :
    CarryGeometry.rawExpansionValue b (emergentDigits b hb n) = n := by
  have hb0 : 0 < b := lt_trans Nat.zero_lt_one hb
  induction n using Nat.strong_induction_on with
  | h n ih =>
      by_cases hn : n = 0
      · subst n
        simp [CarryGeometry.rawExpansionValue, emergentDigits]
      · have hnpos : 0 < n := Nat.pos_of_ne_zero hn
        have hq_lt : emergentQuotient b n < n :=
          emergentQuotient_lt_self b n hb hnpos
        have ihq := ih (emergentQuotient b n) hq_lt
        rw [emergentDigits_of_pos b n hb hnpos]
        simp only [CarryGeometry.rawExpansionValue, Nat.ofDigits]
        rw [ihq]
        simpa [Nat.mul_comm, Nat.add_comm] using
          (emergent_decomposition_value b n hb0).symm

/-- Every recursively extracted digit belongs to the finite local alphabet. -/
theorem emergentDigits_digits_admissible
    (b n : ℕ) (hb : 1 < b) :
    ∀ digit ∈ emergentDigits b hb n,
      CarryGeometry.IsAdmissibleDigit b digit := by
  have hb0 : 0 < b := lt_trans Nat.zero_lt_one hb
  induction n using Nat.strong_induction_on with
  | h n ih =>
      by_cases hn : n = 0
      · subst n
        simp
      · have hnpos : 0 < n := Nat.pos_of_ne_zero hn
        have hq_lt : emergentQuotient b n < n :=
          emergentQuotient_lt_self b n hb hnpos
        rw [emergentDigits_of_pos b n hb hnpos]
        intro digit hdigit
        rcases List.mem_cons.mp hdigit with rfl | hdigit
        · exact emergentRemainder_lt b n hb0
        · exact ih (emergentQuotient b n) hq_lt digit hdigit

/-- A positive quantity's emergent representation has a nonzero final digit. -/
theorem emergentDigits_getLast_ne_zero
    (b n : ℕ) (hb : 1 < b) (hn : n ≠ 0) :
    (emergentDigits b hb n).getLast
      ((emergentDigits_ne_nil_iff_ne_zero b n hb).2 hn) ≠ 0 := by
  have hb0 : 0 < b := lt_trans Nat.zero_lt_one hb
  induction n using Nat.strong_induction_on with
  | h n ih =>
      have hnpos : 0 < n := Nat.pos_of_ne_zero hn
      have hq_lt : emergentQuotient b n < n :=
        emergentQuotient_lt_self b n hb hnpos
      by_cases hq : emergentQuotient b n = 0
      · have hrne : emergentRemainder b n ≠ 0 := by
          intro hr
          have hvalue := emergent_decomposition_value b n hb0
          rw [hq, hr] at hvalue
          simp at hvalue
          exact hn hvalue
        have htail : emergentDigits b hb (emergentQuotient b n) = [] := by
          rw [hq, emergentDigits_zero]
        rw [emergentDigits_of_pos b n hb hnpos]
        rw [htail]
        simpa using hrne
      · have htailne :
            emergentDigits b hb (emergentQuotient b n) ≠ [] :=
          (emergentDigits_ne_nil_iff_ne_zero b (emergentQuotient b n) hb).2 hq
        have ihlast := ih (emergentQuotient b n) hq_lt hq
        rw [emergentDigits_of_pos b n hb hnpos]
        rw [List.getLast_cons htailne]
        exact ihlast

/-- A nonempty emergent digit list has no zero in its most significant position. -/
theorem emergentDigits_no_leading_zero
    (b n : ℕ) (hb : 1 < b) :
    ∀ h : emergentDigits b hb n ≠ [],
      (emergentDigits b hb n).getLast h ≠ 0 := by
  intro h
  have hn : n ≠ 0 := (emergentDigits_ne_nil_iff_ne_zero b n hb).1 h
  simpa using emergentDigits_getLast_ne_zero b n hb hn

/--
The emergent digit list is already a fixed point of Carry Geometry's canonical
normalization: it has the right value, all digits are admissible, and it has no
leading zero.
-/
theorem normalizeEmergentDigits_eq_self
    (b n : ℕ) (hb : 1 < b) :
    CarryGeometry.normalizeCoefficients b (emergentDigits b hb n) =
      emergentDigits b hb n := by
  exact CarryGeometry.normalizeCoefficients_eq_self
    b hb (emergentDigits b hb n)
    (emergentDigits_digits_admissible b n hb)
    (emergentDigits_no_leading_zero b n hb)

/--
Final downstream crosswalk: the independently constructed emergent digit list
is exactly the standard canonical base-`b` digit list.
-/
theorem emergentDigits_eq_natDigits
    (b n : ℕ) (hb : 1 < b) :
    emergentDigits b hb n = Nat.digits b n := by
  have hnorm := normalizeEmergentDigits_eq_self b n hb
  change Nat.digits b
      (CarryGeometry.rawExpansionValue b (emergentDigits b hb n)) =
        emergentDigits b hb n at hnorm
  rw [rawExpansionValue_emergentDigits b n hb] at hnorm
  exact hnorm.symm

/-- The canonical standard digit list therefore inherits the emergent provenance. -/
theorem natDigits_are_emergentDigits
    (b n : ℕ) (hb : 1 < b) :
    Nat.digits b n = emergentDigits b hb n :=
  (emergentDigits_eq_natDigits b n hb).symm

end QuantityRepresentationFoundations
