import QuantityRepresentationFoundations.ClassicalQRCrosswalk
import CarryGeometry.Normalization

/-!
# Bridge to Carry Geometry normalization

The quotient/remainder coordinates in this project were derived from faithful
finite-state representation, unbounded information depth, unit-step dynamics,
local recurrence, and emergent cycle capacity before being identified with the
classical Euclidean operations.

This module connects that independently derived structure to the normalization
API of `carry-geometry`.

The bridge has a precise direction:

1. `emergentRemainder` is the local residual coordinate and
   `emergentQuotient` is the completed-cycle coordinate;
2. together they form a bounded, value-preserving coefficient normalization;
3. the uniqueness theorem in `CarryGeometry.Normalization` therefore identifies
   them with `normalizedDigit` and `carryUnits`;
4. local saturation is exactly the dynamic event whose normalized image is
   digit zero plus one transported carry unit.

Thus carry normalization is not introduced here as a primitive.  It is reached
as the positional reading of the earlier emergent cycle dynamics.
-/

namespace QuantityRepresentationFoundations

/--
The independently constructed emergent coordinates already satisfy the exact
coefficient-normalization predicate used by `carry-geometry`.
-/
theorem emergentCoordinates_are_carryGeometryNormalization
    (b a : ℕ) (hb : 0 < b) :
    CarryGeometry.IsCoefficientNormalization b a
      (emergentRemainder b a) (emergentQuotient b a) := by
  have h := emergentQuotientRemainder_spec b a hb
  constructor
  · exact h.2
  · calc
      emergentRemainder b a + b * emergentQuotient b a =
          emergentQuotient b a * b + emergentRemainder b a := by ac_rfl
      _ = a := h.1.symm

/--
The emergent residual coordinate is exactly the normalized digit of
`carry-geometry`.
-/
theorem emergentRemainder_eq_normalizedDigit
    (b a : ℕ) (hb : 0 < b) :
    emergentRemainder b a = CarryGeometry.normalizedDigit b a := by
  exact ((CarryGeometry.coefficient_normalization_unique b a
    (emergentRemainder b a) (emergentQuotient b a) hb).1
      (emergentCoordinates_are_carryGeometryNormalization b a hb)).1

/--
The emergent completed-cycle coordinate is exactly the number of carry units of
`carry-geometry`.
-/
theorem emergentQuotient_eq_carryUnits
    (b a : ℕ) (hb : 0 < b) :
    emergentQuotient b a = CarryGeometry.carryUnits b a := by
  exact ((CarryGeometry.coefficient_normalization_unique b a
    (emergentRemainder b a) (emergentQuotient b a) hb).1
      (emergentCoordinates_are_carryGeometryNormalization b a hb)).2

/--
Canonical bridge: the pair generated by unit-step cycle dynamics is exactly the
`(carryUnits, normalizedDigit)` data of positional normalization.
-/
theorem emergentCoordinates_eq_carryGeometryNormalization
    (b a : ℕ) (hb : 0 < b) :
    emergentQuotient b a = CarryGeometry.carryUnits b a ∧
      emergentRemainder b a = CarryGeometry.normalizedDigit b a :=
  ⟨emergentQuotient_eq_carryUnits b a hb,
    emergentRemainder_eq_normalizedDigit b a hb⟩

/--
The classical QR crosswalk and the Carry Geometry normalization crosswalk agree
literally: quotient is carry count and remainder is normalized local digit.
-/
theorem classicalQR_eq_carryGeometryNormalization
    (b a : ℕ) (hb : 0 < b) :
    a / b = CarryGeometry.carryUnits b a ∧
      a % b = CarryGeometry.normalizedDigit b a := by
  constructor
  · rw [← emergentQuotient_eq_div b a hb]
    exact emergentQuotient_eq_carryUnits b a hb
  · rw [← emergentRemainder_eq_mod b a hb]
    exact emergentRemainder_eq_normalizedDigit b a hb

/--
Before saturation, the emergent quotient/carry count stays fixed while the
normalized local digit advances by one.
-/
theorem emergent_step_inside_cycle_is_noCarry
    {b n : ℕ}
    (hb : 0 < b)
    (hnext : emergentRemainder b n + 1 < b) :
    CarryGeometry.carryUnits b (n + 1) = CarryGeometry.carryUnits b n ∧
      CarryGeometry.normalizedDigit b (n + 1) =
        CarryGeometry.normalizedDigit b n + 1 := by
  obtain ⟨hq, hr⟩ := emergent_step_inside_cycle hnext
  constructor
  · rw [← emergentQuotient_eq_carryUnits b (n + 1) hb,
        ← emergentQuotient_eq_carryUnits b n hb]
    exact hq
  · rw [← emergentRemainder_eq_normalizedDigit b (n + 1) hb,
        ← emergentRemainder_eq_normalizedDigit b n hb]
    exact hr

/--
At saturation, the dynamic update increments the completed-cycle/carry count by
one and resets the local normalized digit to zero.
-/
theorem emergent_step_at_boundary_is_oneCarry
    {b n : ℕ}
    (hb : 0 < b)
    (hboundary : emergentRemainder b n + 1 = b) :
    CarryGeometry.carryUnits b (n + 1) = CarryGeometry.carryUnits b n + 1 ∧
      CarryGeometry.normalizedDigit b (n + 1) = 0 := by
  obtain ⟨hq, hr⟩ := emergent_step_at_boundary hboundary
  constructor
  · rw [← emergentQuotient_eq_carryUnits b (n + 1) hb,
        ← emergentQuotient_eq_carryUnits b n hb]
    exact hq
  · rw [← emergentRemainder_eq_normalizedDigit b (n + 1) hb]
    exact hr

/--
The first full local cycle, reached from the maximal residual state by one unit
step, is exactly the canonical `carry-geometry` normalization `(digit,carry) =
(0,1)`.
-/
theorem firstSaturation_is_maxDigit_add_one_normalization
    (b : ℕ) (hb : 0 < b) :
    emergentRemainder b (b - 1 + 1) = 0 ∧
      emergentQuotient b (b - 1 + 1) = 1 := by
  have hcarry := CarryGeometry.maxDigit_add_one_normalizes b hb
  constructor
  · rw [emergentRemainder_eq_normalizedDigit b (b - 1 + 1) hb]
    exact hcarry.1
  · rw [emergentQuotient_eq_carryUnits b (b - 1 + 1) hb]
    exact hcarry.2

/--
For a dynamically emergent local capacity, the local residual/cycle-count pair
is exactly the positional digit/carry pair of `carry-geometry`.
-/
theorem emergentLocalCapacity_eq_carryGeometryNormalization
    {Q LocalState : Type*}
    (trajectory : UnitTrajectory Q)
    (model : AutonomousLocalDynamics trajectory LocalState)
    {b : ℕ}
    (hb : EmergentLocalCapacity trajectory model b)
    (n : ℕ) :
    emergentQuotient b n = CarryGeometry.carryUnits b n ∧
      emergentRemainder b n = CarryGeometry.normalizedDigit b n :=
  emergentCoordinates_eq_carryGeometryNormalization b n hb.1.1

end QuantityRepresentationFoundations
