import QuantityRepresentationFoundations.ConstructiveCarryRigidity

#print axioms QuantityRepresentationFoundations.ExplicitLosslessWindow.decode_encode
#print axioms QuantityRepresentationFoundations.ExplicitLosslessWindow.encode_decode
#print axioms QuantityRepresentationFoundations.ExplicitLosslessWindow.successor_encode
#print axioms QuantityRepresentationFoundations.ExplicitLosslessWindow.projection_encode
#print axioms QuantityRepresentationFoundations.ExplicitLosslessWindow.projection_zero
#print axioms QuantityRepresentationFoundations.ExplicitLosslessWindow.projection_commutes_successor
#print axioms QuantityRepresentationFoundations.LosslessCompressedWindow.windowSuccessor_eq_zero_iff_carry
#print axioms QuantityRepresentationFoundations.canonicalDepthProjectionLE_zero
#print axioms QuantityRepresentationFoundations.canonicalDepthProjectionLE_commutes_successor
#print axioms QuantityRepresentationFoundations.canonicalDepthProjectionLE_comp
#print axioms QuantityRepresentationFoundations.windowSuccessor_mk_of_succ_lt
